apiVersion: v1
kind: Service
metadata:
  name: {{ include "s4.fullname" . }}
  labels:
    {{- include "s4.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: {{ if include "s4.tlsActive" . }}https{{ else }}http{{ end }}
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "s4.selectorLabels" . | nindent 4 }}
